#!/bin/bash

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

if [[ $machine == "Linux" ]]
then
  echo "Detected ${machine} environment. Building."

  # Set GCC-9 as compiler for CUDA compatibility
  export CC=/usr/bin/gcc-9
  export CXX=/usr/bin/g++-9
  export CUDAHOSTCXX=/usr/bin/g++-9

  source ../.venv/bin/activate
  cd dry/
  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
  cd ..
  source workon
  cd wet/
  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_C_COMPILER=${CC} -DCMAKE_CXX_COMPILER=${CXX}
  cd ..
  source workon

  cd dry/build/open3d_colcon/
  make install-pip-package -j${nproc}
fi

if [[ $machine == "Mac" ]]
then
  echo "Detected ${machine} environment. Building with CPU support only."

  touch ./wet/src/sogmm_open3d/COLCON_IGNORE

  source .venv/bin/activate
  cd dry/
  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  cd ..
  source workon
  cd wet/
  colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
  cd ..
  source workon

  numcores=$(sysctl -n hw.logicalcpu)
  cd dry/build/open3d_colcon/
  make install-pip-package -j${numcores}
fi
