#!/bin/bash

CWD="$(pwd)"
DRY_INSTALL_DIR="${CWD}/dry/install"
WET_INSTALL_DIR="${CWD}/wet/install"

if [ -d ./.venv ]; then
    source ./.venv/bin/activate
fi

if [ -f $DRY_INSTALL_DIR/setup.sh ]; then
    source $DRY_INSTALL_DIR/setup.sh

    # Add dry install directory to CMAKE_PREFIX_PATH for CMake's find_package()
    export CMAKE_PREFIX_PATH="$DRY_INSTALL_DIR:$CMAKE_PREFIX_PATH"

    for f in ./dry/install/*; do
	if [ -d "$f" ]; then
	    PACKAGE_DIR="$( basename "$f" )"
	    package="$DRY_INSTALL_DIR/$PACKAGE_DIR"
	    eval 'export PYTHONPATH=$package:$PYTHONPATH'
	    eval 'export PATH=$package:$PATH'
	    # Add each package directory to CMAKE_PREFIX_PATH
	    eval 'export CMAKE_PREFIX_PATH=$package:$CMAKE_PREFIX_PATH'
	fi
    done
fi

if [ -f $WET_INSTALL_DIR/setup.sh ]; then
   source $WET_INSTALL_DIR/setup.sh

   # Add wet install directory to CMAKE_PREFIX_PATH
   export CMAKE_PREFIX_PATH="$WET_INSTALL_DIR:$CMAKE_PREFIX_PATH"

   for f in ./wet/install/*; do
       if [ -d "$f" ]; then
	   PACKAGE_DIR="$( basename "$f" )"
	   package="$WET_INSTALL_DIR/$PACKAGE_DIR"
	   eval 'export PYTHONPATH=$package:$PYTHONPATH'
	   eval 'export PATH=$package:$PATH'
	   # Add each package directory to CMAKE_PREFIX_PATH
	   eval 'export CMAKE_PREFIX_PATH=$package:$CMAKE_PREFIX_PATH'
	   # Handle editable (egg-link) installs: add the source path they point to
	   for egglink in $package/lib/python*/site-packages/*.egg-link; do
	       if [ -f "$egglink" ]; then
		   eggpath="$(head -1 $egglink)"
		   eval 'export PYTHONPATH=$eggpath:$PYTHONPATH'
	       fi
	   done
       fi
   done
fi

eval 'export PYTHONWARNINGS="ignore"'
